### ISSUE TITLE
Docker run doesn't stop

### ISSUE THREAD

**Issue by jax79sg** [flavienbwk/apt-mirror-docker#3]
Hi, the apt-mirror simply runs and didn't exit from the docker run. Network activity is zero as well. So did it finish?

**Comment by flavienbwk** [comment]
Hi @jax79sg, thank you for your interest in apt-mirror-docker.

Could you please attach here a screenshot of the logs of your container? (`docker logs <container_id>`)

**Comment by jax79sg** [comment]
Hi, i tried leaving running for another day and it finally stopped after retrieving another 22GB with on-off downloads. Thanks.
