### ISSUE TITLE
apt-mirror appears not to complete download

### ISSUE THREAD

**Issue by k-s-dean** [flavienbwk/apt-mirror-docker#4]
Hi, Thanks for packaging all this up but wondering if you could help.

apt-mirror appears to get to the end of all available downloads but once completed and run again, there seems to be some additional archives / files that need to be downloaded but apt-mirror appears to complete without downloading these additional archives / packages. 

Is this a red hearing or a problem with the perl script ? 

out put below. 

```
Downloading 608 index files using 20 threads...
Begin time: Fri Dec  4 11:45:00 2020
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Fri Dec  4 11:45:03 2020

Processing translation indexes: [TTTTTTTTTTTTTTTTTTTT]

Downloading 1713 translation files using 20 threads...
Begin time: Fri Dec  4 11:45:03 2020
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Fri Dec  4 11:45:04 2020

Processing DEP-11 indexes: [DDDDDDDDDDDDDDDDDDDD]

Downloading 233 dep11 files using 20 threads...
Begin time: Fri Dec  4 11:45:04 2020
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Fri Dec  4 11:45:04 2020

Processing SHA256 by-hash files [DDDDDDDDDDDDDDDDDDDD]

Downloading 5713 by-hash-SHA256 files using 20 threads...
Begin time: Fri Dec  4 11:45:04 2020
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Fri Dec  4 11:45:54 2020

Processing indexes: [PPPPPPPPPPPPPPPPPPPP]

1.5 GiB will be downloaded into archive.
Downloading 40 archive files using 20 threads...
Begin time: Fri Dec  4 11:46:09 2020
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Fri Dec  4 11:46:09 2020
```

Kind regards, 

K

**Comment by k-s-dean** [comment]
To answer my own question and to save others from scratching their head. 

Turns out that for whatever reason incomplete downloads appear to get processed as if they are complete. 

To debug this I added the following perl code at the main download section. 

```
######################################################################################
## Main Download
my $k;
my $v;
while ( ($k,$v) = each %urls_to_download ) {
        my $bytes_human = format_bytes($v);
        print "$k => $bytes_human\n";
}
```

This will spit out incomplete downloads which can then be removed and re-downloaded by running apt-mirror again.

Kind regards ,

K

**Comment by flavienbwk** [comment]
Thank you very much for your contribution @k-s-dean, would you like to open a pull request ?

**Comment by k-s-dean** [comment]
Sure, Once i'm back in work on monday I'll create a pull request. additionally have another fix that needs to be added.

if your volume that you mount into the docker container does not contain a partition number, for example on my VPS.
```
/dev/sda 
```
then the df command that is piped through awk  will print the percentage rather than the the actual partition size causing the script to print the warning saying it needs more space when there is plenty available.

the fix is to use --output=avail on the df command as a flag like so. 

```
my $command = "df --output=avail $directory | awk -F '[^0-9]*' 'NR==2 {print}'";
```

which works for both `sda` and `sda1`

**Comment by flavienbwk** [comment]
@k-s-dean Do you think you'll have the time to push a pull request ? Should I push the edits ? Thanks

**Comment by flavienbwk** [comment]
Please re-open if you observe the problem again.
