### ISSUE TITLE
Support armhf

### ISSUE THREAD

**Issue by Paulpatou** [flavienbwk/apt-mirror-docker#5]
Hi

Could you add the support for armhf? (Raspberry)

I found a documentation to modify the apt-mirror binary but I can't find the lines to modify (Chapter V)
https://blog.debugo.fr/rasbperry-monter-miroir-raspbian/

Thanks

**Comment by flavienbwk** [comment]
Did you try to just set the [defaultarch](https://github.com/flavienbwk/apt-mirror-docker/blob/master/mirror.list#L6) property to `armhf` ?

**Comment by flavienbwk** [comment]
Stale issue.
